# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151026130304 on 2015-11-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Short_Description', models.CharField(max_length=200)),
                ('Detailed_Description', models.TextField(max_length=1000)),
                ('Location_of_Event', models.CharField(max_length=100)),
                ('Attachments', models.FileField(blank=True, upload_to='report')),
                ('sensitivity', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitivity', models.IntegerField(choices=[(3, 'public'), (2, 'private')])),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
